name: Docker-Image

on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get Repo Info
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major"
        minor_pattern: "minor"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
        
    - name: Docker Login en Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      run: 
         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build Docker Image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      run:
         docker build -t $DOCKER_USER/$DOCKER_REPO:1.0.0 .
         docker build -t $DOCKER_USER/$DOCKER_REPO::latest .

    - name: Push Docker Image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      run:
         docker push $DOCKER_USER/$DOCKER_REPO:1.0.0
         docker push $DOCKER_USER/$DOCKER_REPO:latest

  
      
    
